# Generated by Django 4.0.2 on 2022-02-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_remove_topic_image_entry_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='title',
            new_name='label',
        ),
    ]
